### ISSUE TITLE
Categories need to be enabled for pages on the site

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-child-about-us-research#3]
This is so that we can use the category specific features such as hiding pages from menu.

We do this on TNA using a plugin but it isn't necessary and I'm looking to remove the plugin completely as this can be done with about five lines of code in functions.php

```
function enable_categories_on_pages() {
    register_taxonomy_for_object_type('post_tag', 'page'); 
    register_taxonomy_for_object_type('category', 'page');  
}
add_action( 'init', 'enable_categories_on_pages' );
```

**Comment by punalsc** [comment]
I'v pasted in the code above, and now merged into develop.

**Comment by grange85** [comment]
Thanks @punalsc
